### PR TITLE
Update README.md for newbie

### PR DESCRIPTION
**Pull request by h3x4n1um**
I make a few change in README.md to help newbie use it :)

### CODE REVIEW

**Comment by hanipouspilot** [comment]
This repo is obsolete since the focaltech code has been merged to mainstream kernels. There is no need to use it by newbies.

**Comment by h3x4n1um** [comment]
Oh! Sorry

**Comment by deb0ch** [comment]
A lot of people still use an older kernel, including me at the moment as I am required to use the 14.04 version of Ubuntu for my current project.

So I think that this repo hasn't lost all of its usefulness yet.

Is this why your ppa doesn't exist anymore ?

By the way, @hanipouspilot, thank you so much for developing this. It so saved my life, made me happy again. Without it my computer under Linux would never had been the same.

Love it :heart:

**Comment by hanipouspilot** [comment]
@deb0ch

You can use the 4.4 kernel with Ubuntu 14.04. It is officially supported. 
And I did not develop this driver. I just helped to use it.

**Comment by deb0ch** [comment]
Oh, my bad, I didn't go as far as reading the headers :sweat_smile: 

Anyways, you still saved my life by making it more accessible, I don't know if I would have found it otherwise :wink:

**Pull request closed without merging**
